### ISSUE TITLE
Prometheus image path as config vs resource

### ISSUE THREAD

**Issue by jameinel** [canonical/prometheus-operator#2]
The general recommendation from Juju is to use a Resource of type "oci-image" for the image that a charm would use for the application.
This is because it allows us to snapshot an exact digest during "charm publish" times, while still allowing an override by the user during deploy.

For example:
https://github.com/juju-solutions/bundle-kubeflow/blob/master/charms/dex-auth/metadata.yaml

I realize that Mattermost did not do this, but as Prometheus is going to be our example charm, we want to align with the recommended path so others who are copying this follow suite.

**Comment by mthaddon** [comment]
Is snapshotting an exact digest at publish time what we want here? How would security updates be handled, for instance?

**Comment by jameinel** [comment]
By the charm author publishing a new version. The store is the part that is
taking the snapshot.
There is some plans on Rocks to do that with channels but it is
functionally the same.  The charm specifies a series to deploy which gets
snapshotted and updated at the store instead of in the charm.
(there are docker images that do the same with rolling tags, but not all do)

**Comment by balbirthomas** [comment]
@jlounder @jameinel  Is this a recommended way (library) to implement OCI image resources in charms ? If so, kindly do let me know and I will adopt that.

**Comment by dstathis** [comment]
I think this can be closed now?

**Comment by balbirthomas** [comment]
Yes.
