### ISSUE TITLE
Feature request: actions to manage a pool of "static" endpoints.

### ISSUE THREAD

**Issue by spads-spads** [canonical/prometheus-operator#24]
This approach seems extremely promising, and I wonder if we could have some actions to help with migration pains.  In particular, if there could be a manually-curated list of scraped endpoints either managed from juju config or via actions.

The idea would be that there could be legacy systems unreachable via cross-model relations from a new install of this prometheus service, but which need to be considered in alert or graphing queries.  So either a simple list of endpoint URLs to scrape in the config, or a CRUD interface through actions to manage a similar list, would help the "We can't scrape our old *x* until we migrate it" problem.

**Comment by mmanciop** [comment]
Duplicate of #26

**Comment by balbirthomas** [comment]
Closing based on advise to close #26
