### ISSUE TITLE
Ingress relation for Prometheus

### ISSUE THREAD

**Issue by balbirthomas** [canonical/prometheus-operator#25]
## Introduction
The purpose of this issue is to gather requirements and refine implementation design related to use cases for an ingress controller for the Prometheus operator charm. A couple of alternatives are

1. Only allow relations from charms in the same model. If this is the case no ingress controller relation is required for Prometheus.
2. Provided an ingress controller relation and allow scrapping of data from any related charm. However for security reasons only support Grafana relation within the same model since this relation allows data exfiltration. This still leaves open the possibility of data poisoning by charms outside the model. 
3. Support cross model relations of any type dynamically. This implies the Prometheus charm will detect if an incoming relation (scrape target, alertmanager, grafana, ...etc.) are intra-model or cross model. For cross model relation the charm will only accept and provide public IP addresses, and in all other cases the Prometheus charm will provide private IP address and accept private IP addresses.

**Comment by spads-spads** [comment]
As I've mentioned in #26, I think that a single URL can capture all of the information you'd need about a remote endpoint, and Python's `urlparse` gives you a reliable way to extract fields from it.

**Comment by xavpaice** [comment]
By not implementing an ingress, we are specifically excluding access to Prometheus by end users.  Is this something we really want to do?  It's a very useful interface and would be a loss compared to cs:prometheus2.

**Comment by balbirthomas** [comment]
Closing this since Prometheus has an ingress relation now. A new ticket can be created for any future enhancements.
