### ISSUE TITLE
Should charm library use stored state ?

### ISSUE THREAD

**Issue by balbirthomas** [canonical/prometheus-operator#32]
The Prometheus charm library currently uses stored state to save it's list of scape targets. This was motivated by the need to allow use of the library independent of whether a Prometheus relation was instantiated at the time when `add_endpoint` was invoked. However stored state is a per unit state and hence this may be problematic.

**Comment by jameinel** [comment]
If it is something that is being tracked as application data, then I would
put it into a peer relation so that it is preserved for all peers to see.
StoredState is for a charm to track where it is at relative to its
application, but overall application (eg, password for a remote app) would
belong in relation data.

**Comment by balbirthomas** [comment]
Thank you @jameinel .  Permit me to provide a bit more context. It is my endeavour to imbue the two methods `add_endpoint()` and `remove_endpoint()` with the following properties

1. They can be invoked at any time in the client charm's lifecycle. Perhaps even if the system administrator has not created a relation between the client charm and the Prometheus charm.
2. They do not depend on the point of invocation being guarded by a `is_leader()` check. It should only be a simple matter for **any** client charm unit to know its own host address and call `add_endpoint()` or `remove_endpoint()` using just that information.
3. They impose very little (if any) constraint on the client charm (for example requiring the client charm must define a peer relation in its metadata).
4. They do not impose complex code flows on the client charm (for example making the client charm responsible for aggregating and passing a list of its peer IPs to the Prometheus charm).
5. They allow multiple relations between Prometheus and the client charm.

If am successful in meeting these conditions then the usage of these two methods by the client charm becomes very simple. Both these methods have one argument the client charm's unit IP address that must be added or removed from the list of Prometheus' scrape targets. Perhaps I am misguided in my efforts but I am trying to push the boundaries of my knowledge here and explore what is possible.

**Comment by jameinel** [comment]
So this is not about the Prometheus charm, but the Prometheus client lib, correct?
With the intent that the local application (say postgresql) can define information about how it would be scraped if it had a prometheus relation.

I'm not sure that you need the ability to think about what you *would* pass, if you aren't related. It seems useful to be able to only do that work in response to a relation-created/joined/changed.

What is the use for multiple Prometheus relations? To support multiple aggregators? Seems interesting.

If I do understand that this is the client library I can see where some of the other functionality (stored state vs relation data, vs peer relation data) changes a bit.

**Comment by balbirthomas** [comment]
Yes.Indeed the properties are relevant for the Prometheus client lib not the Prometheus charm.

The property that a client  charm is able to use the Prometheus charm library to add a scrape endpoint (invoking `add_endpoint()`) even if the system administrator has not created a Prometheus relation simplifies the use of the charm library. For example the client charm does not need to check that a relation actually exists before calling `add_endpoint()`. Instead `add_endpoint()` can be invoked at any time in the client charm's lifecycle. For example it could be invoked in the `StartEvent`.  I am not sure if this is feasible, if not I will drop the idea. I am trying to explore how far I can simplify the usage of such a charm library.

Having discussed the five properties with @jlounder I stand corrected and the charm library does not need to support multiple relations between the *same* two applications. As far as Prometheus is concerned there does not seem to be a use case for this.

Also an additional configuration option is being considered. This option will allow the client charm to select if all its peer units must be scraped or just one single unit (say the leader) must be scraped.

**Comment by balbirthomas** [comment]
This ticket is quite old. Perhaps a few integration tests can check if the behaviour is as desired. Hence marking this ticket is marked as testing.
