### ISSUE TITLE
Reconsider alertmanager interface name

### ISSUE THREAD

**Issue by mmanciop** [canonical/prometheus-operator#44]
`alertmanager` is not a general relation name, it is more the `interface` of the relation. We need to find a more general name and use it as standard name for relations like "we push alerts".

**Comment by balbirthomas** [comment]
@sed-i May I request you to pick this up as part of you refactor of the Alertmanager Charm library. Feel free to discuss suitable names on channel and with @mmanciop .

**Comment by sed-i** [comment]
@mmanciop, in alertmanager I called it `alerting`. How about that?

Currently:
https://github.com/canonical/prometheus-operator/blob/0e412c999b3b555e7cb0e4de102452e10a111168/metadata.yaml#L31-L35

**Comment by balbirthomas** [comment]
ATTN: @dstathis

**Comment by mmanciop** [comment]
We need to keep it unambiguous with:

* other charms that receive alerts
* other relation names that alertmanager may expose, see, e.g., the Karma ones

IMO, let’s call it `alertmanager_dispatch`
