### ISSUE TITLE
Forwarding Juju topology through intermediate charms

### ISSUE THREAD

**Issue by balbirthomas** [canonical/prometheus-operator#83]
## Introduction
Future revisions of the Prometheus charm may support relations with scrape targets through intermediate charms such as Scrape Target Integrator or Scrape Configuration charm. This may require a workflow for Juju topology labeling where the topology information is passed through from the scrape target via the intermediate charm.

**Comment by mmanciop** [comment]
From [this comment](https://github.com/canonical/prometheus-operator/pull/81#discussion_r683261246), I understand that, in this case, the "charm-in-the-middle" would forward the Juju topology of the actually-scraped charm via the `scrape-metadata`. Right now, I am no longer see a gap that needs addressing.

**Comment by balbirthomas** [comment]
> Right now, I am no longer see a gap that needs addressing.

It might need some refactoring of code flows, which may not be externally visibile. I still need to think this through hence this ticket.

**Comment by balbirthomas** [comment]
I think this ticket is obsolete given we have Metrics Endpoint Aggregator. Hence closing.
